### PR TITLE
Ensure we have all desired openshift client binaries in the qontract-reconcile-base container

### PR DESCRIPTION
**Pull request by jfchevrette**
This adds a script that is used during the docker build to fetch all the desired binaries. 

While this could have been handled in an inline loop in the dockerfile itself (like we do for terraform) I believe doing it like this is more flexible and more robust.

The script makes a couple of assuptions which are documented at the top of the script, mainly around the fact it attempts to find the desired versions in the more stable channels first.

Adding the 4.5, 4.6 and 4.7 binaries adds about 220MB to the image, which is already ~1GB in size

@rporres PTAL

### CODE REVIEW

**Comment by rporres** [comment]
I like the approach of having a separate script for the exact same reasons you mention.

I have the concern of hardcoding versions, which is going to get obsolete very soon. I'd rather get the list of needed major versions for app-interface via a qontract-server query and then download them. The only problem of doing that is that app-interface may change and the query too, but I think it is better than manually maintaining the minor version list. wdyt?

**Comment by jfchevrette** [comment]
Personally I prefer having to maintain a list of versions that really will not change that often (new version every few months maybe?) versus maintaining the external dependency on having to run a query when building the container

I also noticed this is missing something which is having a default oc cli at /usr/bin/oc for backward compatibility. I will add that shortly

**Comment by rporres** [comment]
There's a tie here 😂  Let's see what @apahim thinks, he has the context

**Comment by rrati** [comment]
Late to the party, but IMO we shouldn't put any image into the container and just d/l it.  We can know which one to d/l once native client merges.

**Comment by jfchevrette** [comment]
closing this as native client support (https://github.com/app-sre/qontract-reconcile/pull/1400) is on the way

**Pull request closed without merging**
